pluginManagement {
    repositories {
        // Добавили официальный портал плагинов Gradle, чтобы сервер смог скачать Foojay
        gradlePluginPortal()
        maven { url = "https://fabricmc.net" }
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'shmod'
