pluginManagement {
    repositories {
        // Подняли репозиторий Fabric на первое место, чтобы сборщик сразу нашёл loom
        maven { url = "https://fabricmc.net" }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'shmod'
