name: Build Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21 for Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Setup Java 25 for Minecraft
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '25'

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -Porg.gradle.java.installations.paths=$JAVA_HOME_25_X64
